cd 1
DiplomskiProjekt.exe Config.xml
cd ..
cd 2
DiplomskiProjekt.exe Config.xml
cd ..
cd 3
DiplomskiProjekt.exe Config.xml
cd ..
cd 4
DiplomskiProjekt.exe Config.xml
cd ..
cd 5
DiplomskiProjekt.exe Config.xml
cd ..