cd 6.generacijskiAlgoritam
cd 1
DiplomskiProjekt.exe Config.xml
cd ..
cd 2
DiplomskiProjekt.exe Config.xml
cd ..
cd 3
DiplomskiProjekt.exe Config.xml
cd ..
cd 4
DiplomskiProjekt.exe Config.xml
cd ..
cd 5
DiplomskiProjekt.exe Config.xml
cd ..
cd ..
cd 8.novigeneracijski
cd 1
DiplomskiProjekt.exe Config.xml
cd ..
cd 2
DiplomskiProjekt.exe Config.xml
cd ..
cd 3
DiplomskiProjekt.exe Config.xml
cd ..
cd 4
DiplomskiProjekt.exe Config.xml
cd ..
cd 5
DiplomskiProjekt.exe Config.xml
cd ..